language: cpp

sudo: required

dist: trusty

compiler:
  - gcc

before_install:
  - sudo apt-get install valgrind
  - sudo apt-get update -qq

branches:
  only:
    - master
  
script:
  - $CXX --version
  - echo $CXXFLAGS
  - make
  - valgrind --leak-check=full --show-reachable=yes ./ProjectBloodBowl
 
notifications:
  webhooks: https://webhooks.gitter.im/e/a6fc712ba46449aba1ed
